version: "3"

services:
  api:
    restart: always
    build: ./api/
    ports:
      - "80:8000"
    env_file: ./api/.env
    networks:
      - zomateen_network
    links:
      - "postgresdb:db"

  postgresdb:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - zomateen_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zomateen@123
      - POSTGRES_DB=zomateen
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata:

networks:
  zomateen_network:
    driver: bridge
